//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fila
    {
        public int idFila { get; set; }
        public Nullable<int> idPlayer { get; set; }
        public Nullable<int> ModoJogo { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
