//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogada
    {
        public int idJogada { get; set; }
        public Nullable<int> idJogo { get; set; }
        public Nullable<int> campo { get; set; }
        public Nullable<int> subcampo { get; set; }
        public string simbolo { get; set; }
    
        public virtual Jogo Jogo { get; set; }
    }
}
