//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VelhaEntities1 : DbContext
    {
        public VelhaEntities1()
            : base("name=VelhaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Fila> Fila { get; set; }
        public DbSet<Jogada> Jogada { get; set; }
        public DbSet<Jogo> Jogo { get; set; }
        public DbSet<Player> Player { get; set; }
    }
}
