//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Fila = new HashSet<Fila>();
            this.Jogo = new HashSet<Jogo>();
            this.Jogo1 = new HashSet<Jogo>();
        }
    
        public int idPlayer { get; set; }
        public string userName { get; set; }
        public string senha { get; set; }
        public Nullable<int> rankingNormal { get; set; }
        public Nullable<int> rankingSuper { get; set; }
    
        public virtual ICollection<Fila> Fila { get; set; }
        public virtual ICollection<Jogo> Jogo { get; set; }
        public virtual ICollection<Jogo> Jogo1 { get; set; }
    }
}
